config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :projects, except: [:index, :destroy, :edit, :update]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :subject

  serialize :authors
  enum revision_state: [ :pending, :approved ]
  has_attached_file :attachment, preserve_files: false

  validates_attachment_content_type :attachment, content_type: ['application/pdf']
  validates_attachment_file_name :attachment, :matches => [/pdf\Z/]
  validates :title, :abstract, :subject, :attachment, presence: true
  validates :authors, length: { minimum: 1}
  validates :revision_state, presence: {message: I18n.t('errors.messages.input_revision_state') }, if: "reason.present?"
  validates :reason, presence: {message: I18n.t('errors.messages.input_reason') }, if: "revision_state == \"pending\""

  scope :pending,  -> { where(revision_state: :pending) }
  scope :approved, -> { where(revision_state: :approved) }

  searchable do
    text :title, :abstract, :authors
  end

  def specialty
    subject.specialty
  end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
  enum grade_level: [ :grade, :postgrade, :technicature, :event ]
  has_many :subjects

  validates :name, :grade_level, presence: true


end

app/models/subject.rb
class Subject < ApplicationRecord
  enum department: [ :systems, :electronics, :electric, :civil, :mechanics, :basic_sciences ]
  belongs_to :specialty

  validates :name, :specialty, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :abstract, :date, :subject_id, :revision_state, :authors, :attachment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    q = params[:search]

    unless q.blank?
      @projects = Project.solr_search do
        fulltext q
      end.results
    else
      @projects = Project.approved
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate_text(text, length)
    truncate(text, length: length)
  end
end

app/helpers/enum_i18n_helper.rb
module EnumI18nHelper

  # Returns an array of the possible key/i18n values for the enum
  # Example usage:
  # enum_options_for_select(User, :approval_state)
  def enum_options_for_select(class_name, enum)
    class_name.send(enum.to_s.pluralize).map do |key, _|
      [enum_i18n(class_name, enum, key), key]
    end
  end

  # Returns the i18n version the the models current enum key
  # Example usage:
  # enum_l(user, :approval_state)
  def enum_l(model, enum)
    enum_i18n(model.class, enum, model.send(enum))
  end

  # Returns the i18n string for the enum key
  # Example usage:
  # enum_i18n(User, :approval_state, :unprocessed)
  def enum_i18n(class_name, enum, key)
    I18n.t("activerecord.attributes.#{class_name.model_name.i18n_key}.#{enum.to_s.pluralize}.#{key}")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Prorepo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <%= render 'shared/users/header_nav' %>
      </nav>
      <%= yield %>
      <%= render 'shared/users/footer' %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Campos de Proyecto
      </div>
      <div class="panel-body">
        <%= form_for(project) do |f| %>
          <% if project.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:
              </h2>
              <ul>
                <% project.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <form role="form">
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group col-lg-12">
                    <label><%= f.label :title %></label>
                    <%= f.text_field :title, class: "form-control" %>
                  </div>

                  <div class="form-group col-lg-12">
                    <label><%= f.label :abstract %></label>
                    <%= f.text_area :abstract, style: "resize: none;", rows: "5", class: "form-control" %>
                  </div>

                  <div class="form-group col-lg-12">
                    <label><%= f.label :email %></label>
                    <div class="input-group">
                      <span class="input-group-addon">@</span>
                      <%= f.text_field :email, class: "form-control" %>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group col-lg-12">
                    <label><%= f.label :subject_id %></label>
                    <%= f.select :subject_id, Subject.all.map { |s| [s.name, s.id]}, {include_blank: "Seleccionar..."}, {class: "form-control"} %>
                  </div>

                  <div class="form-group col-lg-12">
                    <label><%= f.label :date %></label>
                    <%= f.date_field :date, class: "form-control" %>
                  </div>

                  <div class="form-group col-lg-12">
                    <label><%= f.label :authors %></label>
                    <%= f.text_field :authors, class: "form-control", placeholder: "Separados por coma. Ejm: Alejandro Lopez, José Perez" %>
                  </div>

                  <div class="form-group col-lg-12">
                    <label><%= f.label :attachment %></label>
                    <%= f.file_field :attachment, type: "file" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="actions">
                  <div class="col-lg-6">
                    <div class="col-lg-12">
                      <%= f.submit class: 'btn btn-default col-lg-4 pull-right' %>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="col-lg-12">
                      <button type="reset" class="btn btn-default col-lg-4 pull-left"><%= I18n.t('reset_button') %></button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
            <!-- /.col-lg-6 (nested) -->
          </div>
          <!-- /.row (nested) -->
        <% end %>
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', root_path %>

app/views/projects/new.html.erb
<div class="col-lg-12" style="min-height: 322px;">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= I18n.t('active_admin.new_model', model: Project.model_name.human) %></h1>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h3><%= @project.title %></h3>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <!-- Nav tabs -->
      <ul class="nav nav-pills">
        <li class="active"><a href="#home-pills" data-toggle="tab">Información</a>
        </li>
        <li><a href="#profile-pills" data-toggle="tab">PDF Adjunto</a>
        </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane fade in active" id="home-pills">
          <div class="col-lg-12">
            <br>
            <p>
              <strong><%= t('activerecord.attributes.project.date') %>:</strong>
              <%= @project.date %>
            </p>

            <p>
              <strong><%= t('activerecord.attributes.project.subject') %>:</strong>
              <%= @project.subject.name %>
            </p>

            <p>
              <strong><%= t('activerecord.attributes.project.authors') %>:</strong>
              <%= @project.authors %>
            </p>

            <p>
              <strong><%= t('activerecord.attributes.project.abstract') %>:</strong>
              <%= @project.abstract %>
            </p>
          </div>
        </div>
        <div class="tab-pane fade" id="profile-pills">
          <% if @project.attachment? %>
            <br>
            <p>
              <div class="col-lg-12">
                <iframe src=<%= @project.attachment.url %> width="100%" height="780"></iframe>
              </div>
            </p>
          <% end %>
        </div>
      </div>
    </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>

app/views/shared/users/_footer.html.erb
<div class="col-lag-12">
  <footer><h5>Powered by Ale Lopez</h5></footer>
</div>

app/views/shared/users/_header_nav.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to I18n.t(:title), root_path, class: "navbar-brand" %>
</div>

app/views/welcome/_search_form.html.erb
<%= form_tag(root_path, :method => "get", id: "search-form") do %>
    <%= search_field_tag :search, params[:search], placeholder: "Buscar Proyectos" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/welcome/index.html.erb
<div class="container" style="min-height: 202px;">
<div class="row">
  <div class="col-lg-6">
    <%= render 'welcome/search_form' %>
  </div>
  <div class="col-lg-6">
    <h1>
      <%= link_to new_project_path, class: "btn btn-primary btn-sm pull-right", role: "button" do %>
        <span class="pull-right">
          ENVIANOS TU PROYECTO
          <i class="fa fa-cloud-upload"></i>
        </span>
      <% end %>
    </h1>
  </div>
</div>
  <% if @projects.any? %>
    <div class="row">
      <div class="col-lg-12">
          <h1><%= I18n.t('activerecord.models.project.other') %></h1>
      </div>
  <!-- /.col-lg-12 -->
    </div>
  <!-- /.row -->
    <div class="row">
      <% @projects.each do |project| %>
        <div class="col-lg-4">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h4><%= truncate_text(project.title, 40) %></h4>
            </div>
            <div class="panel-body">
              Autores: <%= project.authors %><br>
              <%= I18n.t('activerecord.attributes.project.subject') %>: <%= project.subject.name %>
              <p><%= truncate_text(project.abstract, 200) %></p>
            </div>
            <div class="panel-footer">
            <a href="<%= project_path(project) %>" class="btn btn-primary btn-sm" role="button"><i class="fa fa-info-circle"></i> VER INFO</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h1>No hay proyectos</h1>
  <% end %>
</div>